### ISSUE TITLE
How to version this crate

### ISSUE THREAD

**Issue by rotty** [jean-airoldie/zeromq-src-rs#1]
This is intended as a discussion issue, aimed at resolving these two questions:

- How should this crate be versioned? Ideally the versioning scheme should allow mapping the crate version to the corresponding libzmq release. Probably adopting, maybe with adaptions, the scheme that the `openssl` crate uses is a good idea.
- How would that versioning map to git branches? I see that currently the `master` branch tracks libzmq's master. I guess that's fine, but I'm not sure if it's a good idea to publish unreleased snapshots of the libzmq source code to `crates.io`.

**Comment by jean-airoldie** [comment]
Yes. The master branch is quite experimental and might make breaking changes at any time. I think at the very least two parallel versions should be exist: the master branch and the latest release branch.

I'll into what openssl is doing.

**Comment by jean-airoldie** [comment]
The openssl-src crate, from my understanding, is using the following versioning from the [semver spec](https://semver.org/#spec-item-10):
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Following that logic, the current version should be `0.1.2+4.3.1`.

There is a potential issue however since it is stated that:
> Build metadata SHOULD be ignored when determining version precedence

This means that using this versioning a newer libzmq release would not take precedence over a older one.

**Comment by jean-airoldie** [comment]
I found [this issue](https://github.com/rust-lang/crates.io/issues/1059) in cargo relating to this.

**Comment by jean-airoldie** [comment]
We could consider the libzmq gitsubmodule as part of the crate when versioning. This way someone could depend on a specific libzmq version if he wants.

For instance lets say we bump our libzmq version from `4.3.1` to `4.3.2`. We would then also bump the minor version of our crate. We could still use the build metadata.

Here is a an example:
```
# the libzmq dep's minor version was bumped
`0.1.2+4.3.1` => `0.1.3+4.4.0`
# a minor change was made in the crate's logic
`0.1.2+4.3.1` => `0.1.3+4.3.1`
```

But this seems kinda tricky and potentially error prone.

**Comment by jean-airoldie** [comment]
We could also only change the crate's build metadata but that would force new users to use the lastest stable release (since the previous is yanked). However if the `libzmq` introduces a breaking change, it won't be accounted for in the crate's versioning.

Here is an example:
```
# The previous version is yanked, only the new on remains.
`0.1.2+4.3.1` => `0.1.2+4.4.0`
# This is a breaking changed, yet we do not acknowledge it.
`0.1.2+4.3.1` => `0.1.2+5.0.0`
```

**Comment by jean-airoldie** [comment]
I think the first approach is more sound but we should document the procedure to reduce the likelyhood of potential errors.

**Comment by jean-airoldie** [comment]
We could also directly map to libzmq's version but that would not allow use to introduce any API changes exclusive to the crate. Since we likely want this crate to potentially build on currently unsupported platforms (such as windows), this is not realistic.

**Comment by jean-airoldie** [comment]
I think the first versioning scheme, should work pretty well.

**Comment by jean-airoldie** [comment]
I added [versioning information to the readme](https://github.com/jean-airoldie/zeromq-src-rs/blob/master/README.md#versioning) to make that clear.
