### ISSUE TITLE
DEP_ZMQ_INCLUDE output incorrect

### ISSUE THREAD

**Issue by iamthad** [jean-airoldie/zeromq-src-rs#25]
https://github.com/jean-airoldie/zeromq-src-rs/blob/e7dd3b2103c3e5d95376cbe9e11e0be39822367a/src/lib.rs#L422-L426

The header files are placed in `out/source/include`, but `include_dir` is defined as `out/include` (missing `source`).

**Comment by jean-airoldie** [comment]
Alright I pushed a commit. Should do the trick.

Please tell me if this works properly, then I'll do a release.

**Comment by jean-airoldie** [comment]
Alright, I'm gonna assume this fixes your issue and close.

**Comment by iamthad** [comment]
I just tested your latest release and can confirm it fixes the issue. Thank you for the quick fix!
