### ISSUE TITLE
Add libsodium feature in the crate

### ISSUE THREAD

**Issue by conanoc** [jean-airoldie/zeromq-src-rs#32]
libsodium feature is only in the testcrate. Can we have it in the zeromq-src crate also?

**Comment by jean-airoldie** [comment]
The test crate does nothing special. You can simply copy the configuration to your own crate if you need to link to libsodium.

**Comment by jean-airoldie** [comment]
The `DEP_*` env variables are produced during the build and are specific to each library. The specific variables you talk about are described [here](https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/README.md). In this case they are used to indicate the locations of files for the build script.

See [this link](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) for more information.

> I thought the reason that https://github.com/erickt/rust-zmq/issues/357 was because zeromq-src does not support it. Do you have any idea?

There's no reason why libsodium wouldn't be supported. Last time I used zeromq (about 6 years ago), it could link to libsodium just fine. Could be a bug in the windows build script, based on the issue you showed.

**Comment by jean-airoldie** [comment]
You can take a look at [this archived repo](https://github.com/jean-airoldie/libzmq-rs) for an example that should work.

**Comment by conanoc** [comment]
Those env variables are set by sodium side and zmq builders can use them. testcrate's build.rs demonstrates it. Thank you for your kind explanation.

**Comment by jean-airoldie** [comment]
Your welcome.
