### ISSUE TITLE
Cannot link lib sodium

### ISSUE THREAD

**Issue by bartols** [jean-airoldie/zeromq-src-rs#43]
Still problem linking libsodium,  @jean-airoldie  changes the lib.rs:
            println!(
                "cargo:rustc-link-search={:?}",
                libsodium.lib_dir().display()
            );
and it doesn't work. 

For us the correct changes is:
            println!(
                "cargo:rustc-link-search={}",
                libsodium.lib_dir().display()
            );
in that case everything is fine (from {:?} to {})

**Comment by jean-airoldie** [comment]
Closed by 061e96615f4e694f7fd98496cdde1a58b4aaf02a.

**Comment by esemeniuc** [comment]
@bartols i'm still seeing the same error with your master branch. what compile flags do you use?

**Comment by bartols** [comment]
> @bartols i'm still seeing the same error with your master branch. what compile flags do you use?

I enabled features = ["libsodium"], verify that libsodium.lib_dir() has the correct path.
